framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: false

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    php_errors:
        log: true

when@dev:
    framework:
        profiler: { only_exceptions: false }