framework:
    http_client:
        scoped_clients:
            akismet.client:
                base_uri: 'https://%env(AKISMET_API_KEY)%.rest.akismet.com'

            github.client:
                base_uri: 'https://api.github.com'
                headers:
                    Accept: 'application/vnd.github.v3+json'
                    Authorization: 'token %env(GITHUB_API_KEY)%'