commands:
    start:
        help: Start local server
        steps:
            - docker-compose up -d
            - symfony local:server:start -d
            - symfony server:log

    stop:
        help: Stop local server
        steps:
            - docker-compose down
            - symfony local:server:stop

    watch:
        help: Run Yarn watch command
        steps:
            - symfony local:run yarn encore dev-server

    ci:
        help: Run CI tests
        steps:
            - php vendor/bin/php-cs-fixer fix --no-ansi
            - php vendor/bin/phpstan analyse
            - php bin/console lint:container
            - php bin/console lint:yaml config/
            - php bin/console lint:twig templates/
            - yarn run lint --fix