email_contact:
    path: /_email/contact
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'emails/contact.html.twig'
        context:
            name: John Doe
            message: Bonjour, je souhaites juste vous dire bonjour !