parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude: ['../src/Kernel.php']

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Service\AkismetService:
        arguments:
            $akismetApiKey: '%env(AKISMET_API_KEY)%'
            $appDefaultUri: '%env(APP_DEFAULT_URI)%'

    App\Service\GithubService:
        arguments:
            - '%kernel.project_dir%/config/github/repositories.yaml'