github:
    repositories:
        -
            url: https://github.com/IQ2i/prestashop-webservice
            name: IQ2i/prestashop-webservice
            description: A PHP library that let you interact with PrestaShop API
            created_at: 2021-04-28T08:48:16Z
            forked: false
        -
            url: https://github.com/loicsapone/portfolio
            name: loicsapone/portfolio
            description: My own website
            created_at: 2021-05-10T16:07:03Z
            forked: false
        -
            url: https://github.com/IQ2i/data-importer
            name: IQ2i/data-importer
            description: A PHP library to easily manage and import large data file
            created_at: 2021-05-10T16:07:03Z
            forked: false
        -
            url: https://github.com/IQ2i/aergie
            name: IQ2i/aergie
            description: An easy alternative to makefile
            created_at: 2020-09-30T06:50:47Z
            forked: false
        -
            url: https://github.com/IQ2i/prestashop-webservice-bundle
            name: IQ2i/prestashop-webservice-bundle
            description: Symfony bundle to wrap Prestashop official webservice client
            created_at: 2015-04-10T19:32:37Z
            forked: false
        -
            url: https://github.com/loicsapone/symfony-docs
            name: loicsapone/symfony-docs
            description: The Symfony documentation
            created_at: 2010-02-17T08:43:51Z
            forked: true